cloud:
  address: localhost
  ws-port: 8071
  reconnect-timeout: 10s
client:
  addresses:
    - http://localhost:3000
server:
  address: :8090

device:
  id: 535a674a-e515-45be-badb-b901ccb3b4ab
  manufacturer: Zarinit
  model: Router
  model-version: dev
  firmware-version: 0.1.0
