client:
  addresses:
    - http://localhost:3000

server:
  address: :11211

device:
  id: 535a674a-e515-45be-badb-b901ccb3b4ab
  manufacturer: Zarinit
  model: Router
  model-version: dev
  firmware-version: 0.1.0

storage:
  key-value:
    path: /tmp/zarinit-routers-router-key-value-storage

auth:
  security-key: "12345678901234567890123456789012"
