client:
  addresses:
    - http://localhost:3000

server:
  address: :11211

device:
  id: 76c4db34-ad38-4b4c-8234-0aa3810ae1c7
  manufacturer: Zarinit
  model: Router
  model-version: dev
  firmware-version: 0.1.0

storage:
  key-value:
    path: /tmp/zarinit-routers-router-key-value-storage

auth:
  security-key: "12345678901234567890123456789012"
